In [2]:
import numpy as np

## <font color='blue'> Arrange</font>

In [3]:
a=np.arange(1,10)

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## <font color='blue'> Multidimension array</font>

In [6]:
a=np.array([[1,2,3],[4,5,6],[64,34,65]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [64 34 65]]


In [8]:
a.size

9

In [9]:
a.shape

(3, 3)

In [10]:
a.dtype

dtype('int64')

In [11]:
a.ndim

2

In [12]:
type(a)

numpy.ndarray

## Shape function

## Zeros Function

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Ones Function

In [9]:
np.ones((3,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

## <font color='blue'> Eye Function</font>

In [10]:
    np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Reshape function - will not alter the original data

In [19]:
a=np.random.randint(1,15,(3,4))
a

array([[ 7,  5, 11,  8],
       [ 3,  1, 14, 10],
       [ 2, 13,  8,  7]])

In [20]:
a.reshape(6,2)

array([[ 7,  5],
       [11,  8],
       [ 3,  1],
       [14, 10],
       [ 2, 13],
       [ 8,  7]])

In [21]:
a

array([[ 7,  5, 11,  8],
       [ 3,  1, 14, 10],
       [ 2, 13,  8,  7]])

## Resize Function - will change the original data

In [23]:
a.resize(2,6)

In [24]:
a

array([[ 7,  5, 11,  8,  3,  1],
       [14, 10,  2, 13,  8,  7]])

## Linspace Function

In [16]:
np.linspace(1,8,5)

array([1.  , 2.75, 4.5 , 6.25, 8.  ])

## Random function

In [17]:
np.random.seed(7)
np.random.rand(3,4)    #between 0 and 1

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904]])

In [19]:
np.random.randn(3,4)  #return a sample from the "standard normal distribution"

array([[-0.38713994,  2.02907222, -0.04538603, -1.4506787 ],
       [-0.40522786, -2.2883151 ,  1.04939655, -0.41647432],
       [-0.74255353,  1.07247013, -1.65107559,  0.53542936]])

In [21]:
a=np.random.randint(4,20,10)  #10 NUMBERS  between 4 and 20

In [22]:
a.reshape(5,2)

array([[ 5, 15],
       [18, 13],
       [ 9, 13],
       [17,  5],
       [19, 19]])

In [24]:
np.random.randint(2,15,(3,5))   #new thing

array([[ 5, 14,  6,  7, 14],
       [13,  5,  2,  6, 13],
       [10, 12, 12,  8, 13]])

## Flatten

In [26]:
a=np.random.random((4,7))

In [27]:
a

array([[0.13208955, 0.53792259, 0.26175256, 0.51247644, 0.02563616,
        0.67089905, 0.5840681 ],
       [0.89010526, 0.86204263, 0.87006716, 0.99404578, 0.20797456,
        0.81713491, 0.1720685 ],
       [0.4047368 , 0.10383201, 0.98485235, 0.86057475, 0.10498902,
        0.71560604, 0.80461389],
       [0.92424938, 0.03524227, 0.23588737, 0.14667745, 0.84160585,
        0.80671456, 0.83509319]])

In [30]:
a=a.flatten()

In [31]:
a

array([0.13208955, 0.53792259, 0.26175256, 0.51247644, 0.02563616,
       0.67089905, 0.5840681 , 0.89010526, 0.86204263, 0.87006716,
       0.99404578, 0.20797456, 0.81713491, 0.1720685 , 0.4047368 ,
       0.10383201, 0.98485235, 0.86057475, 0.10498902, 0.71560604,
       0.80461389, 0.92424938, 0.03524227, 0.23588737, 0.14667745,
       0.84160585, 0.80671456, 0.83509319])

# <

In [25]:
mn=np.arange(50)

In [26]:
mn[mn<12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Broadcasting

In [30]:
mn[mn>25]=100   #replacing all the numbers more than 25 with 100

In [31]:
mn

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

## Copy Function


mn=n.copy()

## arr.max() ,  arr.min() ,     arr.sum()

## <font color='blue'> Sorting </font>

In [32]:
a=np.random.randint(3,30,(3,5))

In [33]:
a

array([[26,  5,  8, 19, 29],
       [ 3, 14, 13,  8, 16],
       [16, 11,  6, 29,  4]])

In [34]:
np.sort(a,axis=0,kind='heapsort')

array([[ 3,  5,  6,  8,  4],
       [16, 11,  8, 19, 16],
       [26, 14, 13, 29, 29]])

In [35]:
np.sort(a,axis=1,kind='quicksort')

array([[ 5,  8, 19, 26, 29],
       [ 3,  8, 13, 14, 16],
       [ 4,  6, 11, 16, 29]])

In [36]:
np.sort(a)

array([[ 5,  8, 19, 26, 29],
       [ 3,  8, 13, 14, 16],
       [ 4,  6, 11, 16, 29]])

## <font color='blue'> Merge and Split </font>

In [37]:
a1=np.random.randint(2,10,(2,4))
a2=np.random.randint(11,21,(2,4))

In [38]:
a1

array([[6, 4, 5, 4],
       [6, 2, 8, 3]])

In [39]:
a2

array([[15, 20, 13, 12],
       [15, 13, 11, 13]])

In [40]:
np.hstack((a1,a2))

array([[ 6,  4,  5,  4, 15, 20, 13, 12],
       [ 6,  2,  8,  3, 15, 13, 11, 13]])

In [41]:
np.vstack((a1,a2))

array([[ 6,  4,  5,  4],
       [ 6,  2,  8,  3],
       [15, 20, 13, 12],
       [15, 13, 11, 13]])

In [43]:
a=np.concatenate((a1,a2),axis=0)

In [44]:
a

array([[ 6,  4,  5,  4],
       [ 6,  2,  8,  3],
       [15, 20, 13, 12],
       [15, 13, 11, 13]])

In [45]:
np.vsplit(a,2)

[array([[6, 4, 5, 4],
        [6, 2, 8, 3]]),
 array([[15, 20, 13, 12],
        [15, 13, 11, 13]])]

In [46]:
np.vsplit(a,4)

[array([[6, 4, 5, 4]]),
 array([[6, 2, 8, 3]]),
 array([[15, 20, 13, 12]]),
 array([[15, 13, 11, 13]])]

In [47]:
np.hsplit(a,2)

[array([[ 6,  4],
        [ 6,  2],
        [15, 20],
        [15, 13]]),
 array([[ 5,  4],
        [ 8,  3],
        [13, 12],
        [11, 13]])]

In [48]:
np.hsplit(a,4)

[array([[ 6],
        [ 6],
        [15],
        [15]]),
 array([[ 4],
        [ 2],
        [20],
        [13]]),
 array([[ 5],
        [ 8],
        [13],
        [11]]),
 array([[ 4],
        [ 3],
        [12],
        [13]])]